#pragma once
#include <filesystem>
#include <sys/stat.h>
#include <algorithm>
#include <windows.h>
#include <cstdio>
#include <Lmcons.h>
#include <direct.h> 
#include <stdio.h> 
#include <math.h>
#include <string>
#include <vector>
#include <stack>
#include <deque>
#include <set>
#include <map>